services:
  garden_game_manager:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app # This allows for changes to be reflected in the container
      - /var/log/ggm:/var/log/ggm
    networks:
      - ggm-network # Private network for cross container communication
    env_file:
      - .env
      - .env.${ENVIRONMENT}
    environment:
      - LOG_DIR=/var/log/ggm
      - MYSQLHOST=mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ggm-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQLUSER}
      - MYSQL_PASSWORD=${MYSQLPASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - ggm-network
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${MYSQLUSER}
      - PMA_PASSWORD=${MYSQLPASSWORD}
    depends_on:
      - mysql

networks:
  ggm-network:
    driver: bridge

volumes:
  mysql_data:
