services:
  garden_game_manager:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - .:/app # This allows for changes to be reflected in the container
      - /var/log/ggm:/var/log/ggm
    networks:
      - ggm-network # Private network for cross container communication
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - BOT_PREFIX=${BOT_PREFIX}
      - MYSQLHOST=${MYSQLHOST}
      - MYSQLUSER=${MYSQLUSER}
      - MYSQLPASSWORD=${MYSQLPASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - LOG_DIR=${LOG_DIR}

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ggm-network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQLUSER=${MYSQLUSER}
      - MYSQLPASSWORD=${MYSQLPASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - ggm-network
    environment:
      - PMA_HOST=${MYSQLHOST}
      - PMA_USER=${MYSQLUSER}
      - PMA_PASSWORD=${MYSQLPASSWORD}
    depends_on:
      - mysql              # Ensure MySQL starts first

networks:
  ggm-network:
    driver: bridge

volumes:
  mysql_data:
