services:
  garden_game_manager:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env  # This will be used if file exists
    volumes:
      - .:/app
      - /var/log/ggm:/var/log/ggm
    networks:
      - ggm-network
    environment:
      - ENVIRONMENT=prod  # or dev
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - BOT_PREFIX=${BOT_PREFIX}
      - MYSQL_HOST=mysql
      - MYSQL_USER=ggm
      - MYSQL_PASSWORD=ggm
      - MYSQL_DB=ggm
      - LOG_DIR=/var/log/ggm

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ggm-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ggm
      - MYSQL_USER=ggm
      - MYSQL_PASSWORD=ggm

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"          # Map host port 8080 to container port 80
    networks:
      - ggm-network
    environment:
      - PMA_HOST=mysql     # Connect to the MySQL service
      - PMA_USER=ggm
      - PMA_PASSWORD=ggm
    depends_on:
      - mysql              # Ensure MySQL starts first

networks:
  ggm-network:
    driver: bridge           # Use the default bridge network
    
volumes:
  mysql_data:               # Define a volume for MySQL data persistence
