"""Removed remaining points from character model

Revision ID: 01176a2d38f1
Revises: f42408d9e356
Create Date: 2024-12-28 14:01:54.261519

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '01176a2d38f1'
down_revision: Union[str, None] = 'f42408d9e356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'remaining_points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('remaining_points', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
