"""Added gacha_config table

Revision ID: 365ea7ae854b
Revises: 0050450bb063
Create Date: 2024-12-28 15:19:39.416395

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365ea7ae854b'
down_revision: Union[str, None] = '0050450bb063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gachaconfig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('general_pick_price', sa.Integer(), nullable=False),
    sa.Column('choice_pick_price', sa.Integer(), nullable=False),
    sa.Column('pity_threshold', sa.Integer(), nullable=False),
    sa.Column('pity_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gachaconfig')
    # ### end Alembic commands ###
