"""Removed messages count

Revision ID: 6f3fff3d36c5
Revises: b1a365cc91cf
Create Date: 2024-12-22 00:48:58.046595

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f3fff3d36c5'
down_revision: Union[str, None] = 'b1a365cc91cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'message_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('message_count', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
