"""Added active character field

Revision ID: 8b83c1f2cad5
Revises: cf1277ccba90
Create Date: 2024-12-24 00:43:42.217093

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b83c1f2cad5'
down_revision: Union[str, None] = 'cf1277ccba90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active_character_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'character', ['active_character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'active_character_id')
    # ### end Alembic commands ###
