"""Added icon_url for regions

Revision ID: 90d20445a967
Revises: ee48db9e0660
Create Date: 2024-12-23 20:25:41.007685

"""

import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "90d20445a967"
down_revision: Union[str, None] = "ee48db9e0660"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "region",
        sa.Column("icon_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("region", "icon_url")
    # ### end Alembic commands ###
