"""Changed description to be text field

Revision ID: afb261ba9c7a
Revises: cc5a2cb442a4
Create Date: 2024-12-23 21:23:17.208324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "afb261ba9c7a"
down_revision: Union[str, None] = "cc5a2cb442a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "race",
        "description",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "race",
        "description",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
