"""Added character field to users

Revision ID: cf1277ccba90
Revises: afb261ba9c7a
Create Date: 2024-12-23 22:58:57.763618

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "cf1277ccba90"
down_revision: Union[str, None] = "afb261ba9c7a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
