"""Added new character columns

Revision ID: f42408d9e356
Revises: 095c6af2875f
Create Date: 2024-12-25 21:30:13.795982

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42408d9e356'
down_revision: Union[str, None] = '095c6af2875f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character', sa.Column('coins', sa.Integer(), nullable=False))
    op.add_column('character', sa.Column('current_hp', sa.Integer(), nullable=False))
    op.add_column('character', sa.Column('current_mp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character', 'current_mp')
    op.drop_column('character', 'current_hp')
    op.drop_column('character', 'coins')
    # ### end Alembic commands ###
